version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YBMEj/X4BxTlGyuLBEchfdlLIDCTGV0HRO1UnZn9Fpc=
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
